use std::fs::{self, File};
use std::io::{Read, Write};
use std::path::{Path, PathBuf};
use walkdir::WalkDir;
use zip::write::SimpleFileOptions;
use zip::ZipWriter;

const HANDOFF_PATHS: &[&str] = &[
    "README.md",
    "engagement.json",
    "phase-checklist.json",
    "engagement-register.json",
    "ontology-objects.json",
    "02-design/ontology-elements.json",
    "02-design/architecture.json",
    "02-design/design-overview.md",
    "02-design/ontology-design.md",
    "02-design/pipeline-design.md",
    "02-design/workshop-spec.md",
    "03-build/delivery-board.json",
    "03-build/uat-scenarios.json",
    "04-deploy/runbook.md",
    "05-handoff/handoff.md",
];

pub fn export_handoff_pack(root: &Path, project_path: &str, dest_path: &Path) -> Result<(), String> {
    let project_dir = root.join(project_path);
    if !project_dir.is_dir() {
        return Err(format!("Project not found: {project_path}"));
    }
    if dest_path.parent().is_none() {
        return Err("Invalid destination path".into());
    }
    if let Some(parent) = dest_path.parent() {
        fs::create_dir_all(parent).map_err(|e| e.to_string())?;
    }

    let mut files: Vec<PathBuf> = Vec::new();
    for rel in HANDOFF_PATHS {
        let full = project_dir.join(rel);
        if full.is_file() {
            files.push(full);
        }
    }

    let adr_dir = project_dir.join("02-design/adrs");
    if adr_dir.is_dir() {
        for entry in WalkDir::new(&adr_dir)
            .min_depth(1)
            .max_depth(1)
            .into_iter()
            .filter_map(|e| e.ok())
        {
            let path = entry.path();
            if path.is_file() {
                files.push(path.to_path_buf());
            }
        }
    }

    let refs_dir = project_dir.join("references");
    if refs_dir.is_dir() {
        for entry in WalkDir::new(&refs_dir)
            .min_depth(1)
            .into_iter()
            .filter_map(|e| e.ok())
        {
            let path = entry.path();
            if path.is_file() {
                files.push(path.to_path_buf());
            }
        }
    }

    if files.is_empty() {
        return Err("No handoff files found in project".into());
    }

    files.sort();

    let mut manifest = String::from("# Handoff pack index\n\n");
    manifest.push_str(&format!("Project: `{project_path}`\n\n"));
    manifest.push_str("## Included files\n\n");
    for path in &files {
        let rel = path
            .strip_prefix(&project_dir)
            .map_err(|e| e.to_string())?
            .to_string_lossy()
            .replace('\\', "/");
        manifest.push_str(&format!("- {rel}\n"));
    }
    manifest.push_str("\n_Generated by Foundry Engagement Kit_\n");

    let file = File::create(dest_path).map_err(|e| e.to_string())?;
    let mut zip = ZipWriter::new(file);
    let options = SimpleFileOptions::default().compression_method(zip::CompressionMethod::Deflated);

    let manifest_name = format!("{}/HANDOFF-INDEX.md", project_path.trim_end_matches('/'));
    zip.start_file(&manifest_name, options)
        .map_err(|e| e.to_string())?;
    zip.write_all(manifest.as_bytes())
        .map_err(|e| e.to_string())?;

    for path in &files {
        let rel = path
            .strip_prefix(root)
            .map_err(|e| e.to_string())?
            .to_string_lossy()
            .replace('\\', "/");
        zip.start_file(&rel, options).map_err(|e| e.to_string())?;
        let mut buf = Vec::new();
        File::open(path)
            .and_then(|mut f| f.read_to_end(&mut buf))
            .map_err(|e| e.to_string())?;
        zip.write_all(&buf).map_err(|e| e.to_string())?;
    }

    zip.finish().map_err(|e| e.to_string())?;
    Ok(())
}
